#!/usr/bin/env python3
"""The one command. Exit 0 only when the repository is in its best possible condition.

Implements the contract in HEAL.md. Cursor-lane review findings that changed this file:

  X10  STATUS.md was NOT generated by anything -- it was hand-written, claimed to be
       generated in four documents, and HEAL.md recorded an E1 as CLOSED on the strength of
       that false statement. Z4 now RENDERS the status from this run and compares it against
       the committed file. A status page nobody generates is prose with a title.
  X11  Z5 detected an open heal item by matching the literal `**open**` in a row starting
       `| **E1-`. Dropping the bold, or the space, hid an open blocking item. Inverted to
       FAIL CLOSED: a row for E1/E2 that does not explicitly say `closed` counts as open,
       and a table that yields no rows at all is a failure too.
  X19  Z6 iterated `out.split()` over `git ls-files`, so a tracked path containing a space
       split into two unreadable paths that the bare except skipped silently -- a spaced
       file was never leak-scanned. Now `-z`, NUL-separated.
  Z4   was a one-line `"GENERATED" in body.upper()`, which any file containing that word
       passes. It now compares rendered content, the same technique as Z3.

Contract:
  Z1  every control passes, both directions                    -> E2 on failure
  Z2  the adversarial probe hunt reports 0 findings            -> E2 on failure
  Z2b the review-finding cases match their post-fix expectation-> E2 on failure
  Z3  REGISTER.md matches a fresh live compile                 -> E1 on failure
  Z4  STATUS.md matches what this run renders                  -> E1 on failure
  Z5  no E1/E2 row in HEAL.md fails to say `closed`            -> E1 on failure
  Z6  no secrets or absolute home paths in tracked files       -> E1 on failure
  Z7  the published repository description matches its source  -> E1 on failure

Run:   python3 tools/tests/verify_all.py
Exit:  0 clean · 1 failures (listed) · 2 could not run a check at all
"""
from __future__ import annotations

import re
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PY = sys.executable

VOLATILE = (
    re.compile(r"^- \*\*Compiled:\*\*"),
    re.compile(r"^(Generated|Checked|Verified):"),
    re.compile(r"compiled \d{4}-\d{2}-\d{2}"),
)
OVERRIDE = "verify-all: volatile line"

results: list[tuple[str, bool, str]] = []


def _strip_volatile(text: str) -> str:
    return "\n".join(
        OVERRIDE if any(p.search(ln) for p in VOLATILE) else ln
        for ln in text.splitlines()
    ).strip()


def run(args: list[str], timeout: int = 600) -> tuple[int, str]:
    p = subprocess.run(args, capture_output=True, text=True, cwd=str(ROOT), timeout=timeout)
    return p.returncode, (p.stdout or "") + (p.stderr or "")


def check(name: str, ok: bool, detail: str = "") -> None:
    results.append((name, ok, detail))


# ------------------------------------------------------------------ Z1
def z1() -> None:
    code, out = run([PY, "tools/tests/test_validator.py"])
    tail = [l for l in out.splitlines() if "controls satisfied" in l]
    check("Z1 gate controls (both directions)", code == 0,
          (tail[-1] if tail else out.strip()[-60:]) or "no summary line")


# ------------------------------------------------------------------ Z2
def z2() -> None:
    code, out = run([PY, "tools/tests/probe_hunt.py"])
    tail = [l for l in out.splitlines() if "finding" in l]
    check("Z2 adversarial probe hunt (0 findings)", code == 0, tail[-1] if tail else "")


def z2b() -> None:
    code, out = run([PY, "tools/tests/review_probe.py"])
    tail = [l for l in out.splitlines() if "post-fix expectation" in l]
    check("Z2b review findings match post-fix expectations", code == 0,
          tail[-1] if tail else "no summary line")


# ------------------------------------------------------------------ fixtures + self-audit
def fixtures() -> None:
    code, out = run([PY, "tools/tests/make_fixtures.py"])
    if code != 0:
        check("Z1b fixtures generate", False, out.strip()[:80])
        return
    check("Z1b fixtures generate", True, "2 files")
    bad = []
    for f in ("broken-heredoc.yml", "theater.yml"):
        c, _ = run([PY, "tools/validate_workflows.py", f"tools/tests/fixtures/{f}"])
        if c != 1:
            bad.append(f"{f}->{c}")
    check("Z1b bad fixtures REFUSED with exit 1", not bad, ", ".join(bad) or "both refused")
    c, _ = run([PY, "tools/validate_workflows.py", "/nonexistent/probe.yml"])
    check("Z1b missing file ERRORS with exit 3", c == 3, f"exit {c}")


def self_audit() -> None:
    wfs = sorted(str(p.relative_to(ROOT)) for p in (ROOT / ".github/workflows").glob("*.yml"))
    if not wfs:
        check("Z1c this repository has CI", False, "no workflows found")
        return
    c, out = run([PY, "tools/validate_workflows.py", *wfs])
    check("Z1c this repository passes its own gate", c == 0,
          out.strip().splitlines()[-1] if out.strip() else "")


# ------------------------------------------------------------------ Z3
def z3() -> None:
    target = ROOT / "REGISTER.md"
    if not target.exists():
        check("Z3 REGISTER.md matches a fresh compile", False, "missing")
        return
    committed = target.read_text(encoding="utf-8")
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td) / "REGISTER.md"
        # Always LIVE: the register's claim is that every line was checked this run, and its
        # provenance line says so. Compiling from cache would make that line differ and the
        # comparison meaningless. Network failure is a failure of the check, never a pass.
        run([PY, "tools/compile_register.py", "--out", str(tmp)])
        if not tmp.exists():
            check("Z3 REGISTER.md matches a fresh compile", False, "compile produced nothing")
            return
        fresh = tmp.read_text(encoding="utf-8")
    a, b = _strip_volatile(committed), _strip_volatile(fresh)
    if a == b:
        check("Z3 REGISTER.md matches a fresh compile", True, "no substantive drift")
    else:
        import difflib
        d = list(difflib.unified_diff(a.splitlines(), b.splitlines(), lineterm="", n=0))
        check("Z3 REGISTER.md matches a fresh compile", False,
              f"{len(d)} diff lines: {' / '.join(d[2:6])[:100]}")


# ------------------------------------------------------------------ Z5
def z5() -> None:
    """X11 -- FAIL CLOSED. A blocking row that does not say `closed` counts as open."""
    heal = ROOT / "HEAL.md"
    if not heal.exists():
        check("Z5 every E1/E2 row explicitly closed", False, "HEAL.md missing")
        return
    body = heal.read_text(encoding="utf-8")
    found, not_closed = 0, []
    for line in body.splitlines():
        m = re.match(r"^\|\s*\*{0,2}(E[12]-\d+)\*{0,2}\s*\|", line.strip())
        if not m:
            continue
        found += 1
        if not re.search(r"\bclosed\b", line, re.IGNORECASE):
            not_closed.append(m.group(1))
    if found == 0:
        # A reformatted table is a failure, not an empty pass: the ledger must be parseable.
        check("Z5 every E1/E2 row explicitly closed", False,
              "no E1/E2 rows found — the ledger is unparseable or was reformatted")
        return
    check("Z5 every E1/E2 row explicitly closed", not not_closed,
          ", ".join(not_closed) or f"all {found} rows closed")


# ------------------------------------------------------------------ Z6 + Z7
LEAK = re.compile(
    r"(ghp_[A-Za-z0-9]{20,}|gho_[A-Za-z0-9]{20,}|sk-[A-Za-z0-9]{20,}"
    r"|AKIA[0-9A-Z]{16}|-----BEGIN [A-Z ]*PRIVATE KEY|/Users/[A-Za-z0-9._-]+/)"
)


def z6_z7() -> None:
    # X19 -- NUL-separated so a path containing a space is not silently skipped.
    c, out = run(["git", "ls-files", "-z"])
    hits, unreadable = [], []
    for rel in [p for p in out.split("\0") if p]:
        if rel.startswith("tools/workflows/"):
            continue  # cached third-party workflows contain secret-scan regexes
        f = ROOT / rel
        try:
            text = f.read_text(encoding="utf-8")
        except Exception as exc:
            unreadable.append(f"{rel} ({type(exc).__name__})")
            continue
        for i, ln in enumerate(text.splitlines(), 1):
            if LEAK.search(ln):
                hits.append(f"{rel}:{i}")
    detail = ", ".join(hits[:4]) if hits else ("clean" if not unreadable
                                               else f"UNREAD: {', '.join(unreadable[:3])}")
    check("Z6 no secrets or absolute home paths in tracked files", not hits and not unreadable,
          detail)

    # Z7 -- the published description is a claim surface too, typed by hand once and stale
    # within minutes. Asserted against this source, which deliberately contains no counts.
    canonical = (
        "A register that compiles itself: every claim is produced by a named check during "
        "the run. Ships with a pre-push gate that refuses to publish a repository that is "
        "not clean."
    )
    _, live = run(["gh", "api", "repos/marsojuji-cmyk/the-register", "--jq", ".description"])
    live = live.strip()
    check("Z7 repository description matches this source", live == canonical,
          "in sync" if live == canonical else f"live: {live[:64]!r}")


# ------------------------------------------------------------------ Z4: RENDER the status
def render_status() -> str:
    width = max(len(n) for n, _, _ in results)
    rows = "\n".join(
        f"| {n} | {'PASS' if ok else '**FAIL**'} | {d} |" for n, ok, d in results
    )
    passed = sum(1 for _, ok, _ in results if ok)
    return f"""# STATUS

**GENERATED — do not edit.** Rendered by `tools/tests/verify_all.py` from the results of the
run that checked it. Nothing writes this file by hand; if a number here looks wrong, the fix
is in the code that produces it.

A hand-written status page is true on the day it is written and silently false afterwards.
This one is compared against a fresh rendering on every run, so a change in the results
fails the check until the file is regenerated and committed.

Generated: {datetime.now().astimezone().strftime("%Y-%m-%d %H:%M %Z")}

## This run

| check | result | detail |
|---|---|---|
{rows}

{passed}/{len(results)} checks passed — **{len(results)} of the {len(results) + 1} checks this run
performs.** The missing one is the render check itself (`Z4`): it produces this table and therefore
cannot appear inside it. The console prints {len(results) + 1}/{len(results) + 1}; the two numbers
disagreeing here is arithmetic, not drift.

## What this does NOT claim

- That any test **passes**. A `tests/` directory is presence, not correctness.
- That any workflow is **meaningful**. The gate proves a job *can* fail; it does not prove
  the job tests anything worth testing.
- That any code is **correct, secure, or used**.
- That the probe hunt covers cases nobody imagined. It is a second pass by the same lane —
  see the honest note in `tools/tests/probe_hunt.py`.
- Anything about parties outside this account. **The only claim that grants authority is an
  external party depending on, citing, or routing through an artifact.**

## Provenance

The method is identified by content hash in `REGISTER.md`, never by a hand-maintained version
string. Every defect this project has found is in `INCIDENTS.md` with the control it produced;
the disposition of every known gap is in `HEAL.md`; the structural weak spots are in
`WEAK-SPOTS.md`.
"""


def z4() -> None:
    """X10 -- render, compare, and only rewrite when the substance changed."""
    target = ROOT / "STATUS.md"
    fresh = render_status()
    if not target.exists():
        target.write_text(fresh, encoding="utf-8")
        check("Z4 STATUS.md matches this run's rendering", False,
              "was missing; rendered from this run — commit it")
        return
    committed = target.read_text(encoding="utf-8")
    if _strip_volatile(committed) == _strip_volatile(fresh):
        check("Z4 STATUS.md matches this run's rendering", True, "no substantive drift")
        return
    # Rewrite only when the substance changed, so the timestamp does not churn every run.
    target.write_text(fresh, encoding="utf-8")
    check("Z4 STATUS.md matches this run's rendering", False,
          "stale — regenerated on disk; commit it")


def main() -> int:
    for fn in (z1, z2, z2b, fixtures, self_audit, z3, z5, z6_z7):
        try:
            fn()
        except Exception as exc:  # a check that cannot run is a failure, never a pass
            check(f"{fn.__name__} could not run", False, repr(exc)[:110])
    z4()  # last: it renders everything above

    width = max(len(n) for n, _, _ in results)
    failed = 0
    print("VERIFY ALL".ljust(width + 14, "="))
    for name, ok, detail in results:
        if not ok:
            failed += 1
        print(f"{'PASS' if ok else 'FAIL'}  {name:<{width}}  {detail}")
    print("=" * (width + 14))
    print(f"{len(results) - failed}/{len(results)} checks passed")

    if failed:
        print("\nPUSH REFUSED. Nothing reaches GitHub unless it is in its best condition.")
        print("Fix the failure, or record the gap in HEAL.md with a severity, owner and status.")
        return 1
    print("\nCLEAN — safe to publish.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
